apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-service
  namespace: sparkapply-prod
  labels:
    app: application-service
    version: "${IMAGE_TAG}" # Dynamically set by CI/CD pipeline
spec:
  replicas: 2 # Start with 2 replicas, HPA will scale up as needed
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: application-service
  template:
    metadata:
      labels:
        app: application-service
        version: "${IMAGE_TAG}" # Dynamically set by CI/CD pipeline
    spec:
      containers:
      - name: application-service
        image: ghcr.io/frostlab63/sparkapply/application-service:${IMAGE_TAG} # Image built by CI/CD
        ports:
        - containerPort: 3005
        env:
        - name: NODE_ENV # Passed from ConfigMap
          valueFrom:
            configMapKeyRef:
              name: sparkapply-config
              key: NODE_ENV
        - name: PORT # Passed from ConfigMap
          valueFrom:
            configMapKeyRef:
              name: sparkapply-config
              key: PORT_APPLICATION_SERVICE # Define a specific port key in ConfigMap
        - name: DATABASE_URL # Passed from Secret

          valueFrom:
            secretKeyRef:
              name: sparkapply-secrets
              key: database-url
        - name: REDIS_URL # Passed from Secret

          valueFrom:
            secretKeyRef:
              name: sparkapply-secrets
              key: redis-url
        - name: JWT_SECRET # Passed from Secret

          valueFrom:
            secretKeyRef:
              name: sparkapply-secrets
              key: jwt-secret
        - name: USER_SERVICE_URL # Internal Kubernetes service URL
          value: "http://user-service:3001"
        - name: JOB_SERVICE_URL # Internal Kubernetes service URL
          value: "http://job-service:3002"
        - name: ENABLE_NOTIFICATIONS # Passed from ConfigMap
          valueFrom:
            configMapKeyRef:
              name: sparkapply-config
              key: ENABLE_NOTIFICATIONS
        - name: ENABLE_DOCUMENT_PROCESSING # Passed from ConfigMap
          valueFrom:
            configMapKeyRef:
              name: sparkapply-config
              key: ENABLE_DOCUMENT_PROCESSING
        - name: ENABLE_INTERVIEW_SCHEDULING # Passed from ConfigMap
          valueFrom:
            configMapKeyRef:
              name: sparkapply-config
              key: ENABLE_INTERVIEW_SCHEDULING
        resources:
          requests:
            memory: "200Mi" # Adjusted initial request
            cpu: "150m"  # Adjusted initial request
          limits:
            memory: "400Mi" # Adjusted limit
            cpu: "300m"  # Adjusted limit
        livenessProbe:
          httpGet:
            path: /health
            port: 3005
          initialDelaySeconds: 60 # Increased initial delay for service startup
          periodSeconds: 15 # Increased period for less frequent checks
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3005
          initialDelaySeconds: 10 # Adjusted initial delay
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: upload-storage
          mountPath: /app/uploads
      volumes:
      - name: upload-storage
        persistentVolumeClaim:
          claimName: sparkapply-uploads
---
apiVersion: v1
kind: Service
metadata:
  name: application-service
  namespace: sparkapply-prod
  labels:
    app: application-service
spec:
  selector:
    app: application-service
  ports:
  - port: 3005
    targetPort: 3005
    protocol: TCP
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: application-service-hpa
  namespace: sparkapply-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: application-service
  minReplicas: 2 # Matches initial deployment replicas
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60 # Scale up earlier on CPU
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70 # Scale up earlier on Memory
