apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: sparkapply-prod
  labels:
    app: web
    version: "${IMAGE_TAG}" # Dynamically set by CI/CD pipeline
spec:
  replicas: 2 # Start with 2 replicas, HPA will scale up as needed
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        version: "${IMAGE_TAG}" # Dynamically set by CI/CD pipeline
    spec:
      containers:
      - name: web
        image: ghcr.io/frostlab63/sparkapply/web:${IMAGE_TAG} # Image built by CI/CD
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV # Passed from ConfigMap
          valueFrom:
            configMapKeyRef:
              name: sparkapply-config
              key: NODE_ENV
        resources:
          requests:
            memory: "100Mi" # Adjusted initial request
            cpu: "75m"  # Adjusted initial request
          limits:
            memory: "200Mi" # Adjusted limit
            cpu: "150m"  # Adjusted limit
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 45 # Increased initial delay for service startup
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10 # Adjusted initial delay
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: sparkapply-prod
  labels:
    app: web
spec:
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-hpa
  namespace: sparkapply-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web
  minReplicas: 2 # Matches initial deployment replicas
  maxReplicas: 12
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60 # Scale up earlier on CPU
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70 # Scale up earlier on Memory
